version: '3.4'

services:
  dbsqlserver:
    restart: on-failure:8
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - my_network
    user: root
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - PATH=$PATH:/opt/mssql-tools/bin/
      - TZ=America/Sao_Paulo
      - HOSTNAME=dbsqlserver
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} "
        ]
      interval: 2s
      timeout: 2s
      retries: 100
      start_period: 4s
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./data/planilhas/:/app/data/planilhas
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      dbsqlserver:
        condition: service_healthy
    command: >
      sh -c "echo 'Container scraper começou a ser executado!' && python /app/main.py"

networks:
  my_network:
    driver: bridge

volumes:
  mssqldata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db_data/